"""Enumerate Rust's server convars from a real Assembly-CSharp.dll.

Every convar Rust accepts on the command line is a static field or property
carrying a [ServerVar] attribute. Its declaring type gives the prefix, so
ConVar.Server.maxplayers is reachable as +server.maxplayers.

This reads metadata only -- no .NET runtime, no Unity, same approach as
a sibling plugin/tools/dump.py. Defaults come from the field's constant value where
the compiler stored one; fields initialised in a static constructor are
reported as UNKNOWN rather than guessed, because a wrong default in a comment
is worse than an absent one.

    ./venv/bin/pip install dnfile
    ./venv/bin/python tools/convars.py <Assembly-CSharp.dll> > convars.tsv
    ./venv/bin/python tools/convars.py <Assembly-CSharp.dll> --bat > options.bat

STATUS: written against the metadata layout a sibling plugin/tools/dump.py already
relies on, but NOT yet run against a real Assembly-CSharp.dll. Treat its
output as unverified until it has been. See docs/OPEN-QUESTIONS.md.
"""

import sys

try:
    import dnfile
except ImportError:
    sys.exit("dnfile missing:  python3 -m venv venv && ./venv/bin/pip install dnfile")

# Attributes Facepunch puts on a console variable. ServerVar is the one that
# matters for a launcher; the others are listed so we can say why something
# was skipped rather than silently dropping it.
CONVAR_ATTRS = ("ServerVar", "ClientVar", "ReplicatedVar", "AdminVar")


def attr_name(ca):
    """Best-effort name of a CustomAttribute's type."""
    try:
        row = ca.Type.row
        name = getattr(row, "Name", None)
        if name:
            return str(name)
        cls = getattr(row, "Class", None)
        if cls is not None and getattr(cls, "row", None) is not None:
            return str(getattr(cls.row, "TypeName", "?"))
    except Exception:
        pass
    return "?"


def collect(path):
    pe = dnfile.dnPE(path)
    md = pe.net.mdtables

    # member -> [attribute names], keyed the way dump.py does it
    ca_map = {}
    for ca in md.CustomAttribute.rows:
        parent = ca.Parent
        table = parent.table.name if getattr(parent, "table", None) else "?"
        ca_map.setdefault((table, parent.row_index), []).append(attr_name(ca))

    field_index = {id(r): i + 1 for i, r in enumerate(md.Field.rows)}

    # constant values, for the defaults the compiler stored inline
    consts = {}
    for c in getattr(md, "Constant", None).rows if getattr(md, "Constant", None) else []:
        p = c.Parent
        table = p.table.name if getattr(p, "table", None) else "?"
        consts[(table, p.row_index)] = getattr(c, "Value", None)

    out = []
    for td in md.TypeDef.rows:
        ns = str(getattr(td, "TypeNamespace", "") or "")
        tn = str(getattr(td, "TypeName", "") or "")

        # Rust's convar classes live in the ConVar namespace. Keep others out
        # so the list stays a launcher reference, not an assembly dump.
        if ns != "ConVar":
            continue

        prefix = tn.lower()

        for f in (td.FieldList or []):
            row = f.row if hasattr(f, "row") else f
            if row is None:
                continue
            idx = field_index.get(id(row))
            if idx is None:
                continue

            attrs = ca_map.get(("Field", idx), [])
            kinds = [a for a in attrs if any(a.startswith(k) for k in CONVAR_ATTRS)]
            if not kinds:
                continue

            name = str(getattr(row, "Name", "?"))
            default = consts.get(("Field", idx))
            out.append({
                "convar": "%s.%s" % (prefix, name),
                "kind": ",".join(sorted(set(kinds))),
                "default": "UNKNOWN" if default is None else repr(default),
                "type": tn,
            })

    out.sort(key=lambda r: r["convar"])
    return out


def emit_tsv(rows):
    print("convar\tkind\tdefault")
    for r in rows:
        print("%s\t%s\t%s" % (r["convar"], r["kind"], r["default"]))


def emit_bat(rows):
    """Emit launcher option lines, every one commented out.

    Disabled by default on purpose: an option you do not set uses the game's
    default, and a generated launcher that silently sets three hundred convars
    is not a launcher anyone should run.
    """
    print("REM  Generated by tools/convars.py -- every line disabled.")
    print("REM  Remove the leading REM on a line to enable that option.")
    print("REM  A default of UNKNOWN means it is set in a static constructor")
    print("REM  and was not read; check in game with the convar's own name.")
    print()
    current = None
    for r in rows:
        if r["type"] != current:
            current = r["type"]
            print()
            print("REM " + "-" * 66)
            print("REM  %s" % current)
            print("REM " + "-" * 66)
        print("REM  %s  [default: %s]" % (r["convar"], r["default"]))
        print('REM set "ARGS=!ARGS! +%s VALUE"' % r["convar"])


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    rows = collect(sys.argv[1])
    if "--bat" in sys.argv:
        emit_bat(rows)
    else:
        emit_tsv(rows)
    print("\nREM  %d server convars found." % len(rows), file=sys.stderr)
